include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    unawaited_futures: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    directives_ordering: true